import bs58 from 'bs58';
import { describe, it, expect } from 'vitest';
import { validateConfig } from '../../src/environment';

const VALID_HEX = 'a'.repeat(64);
const VALID_SOLANA = bs58.encode(new Uint8Array(64));

const NON_ELISYM_ENV_KEYS = ['SECRET_SALT', 'ELIZA_SERVER_AUTH_TOKEN'] as const;

function envless<T>(fn: () => T, overrides?: Record<string, string | undefined>): T {
  const snapshot: Record<string, string | undefined> = {};
  for (const key of Object.keys(process.env)) {
    if (key.startsWith('ELISYM_')) {
      snapshot[key] = process.env[key];
      delete process.env[key];
    }
  }
  for (const key of NON_ELISYM_ENV_KEYS) {
    snapshot[key] = process.env[key];
    delete process.env[key];
  }
  if (overrides) {
    for (const [key, value] of Object.entries(overrides)) {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    }
  }
  if (
    process.env.ELISYM_ALLOW_UNSECURED_RUNTIME === undefined &&
    !Object.prototype.hasOwnProperty.call(overrides ?? {}, 'ELISYM_ALLOW_UNSECURED_RUNTIME')
  ) {
    process.env.ELISYM_ALLOW_UNSECURED_RUNTIME = 'true';
  }
  try {
    return fn();
  } finally {
    for (const [key, value] of Object.entries(snapshot)) {
      if (value !== undefined) {
        process.env[key] = value;
      } else {
        delete process.env[key];
      }
    }
    delete process.env.ELISYM_ALLOW_UNSECURED_RUNTIME;
  }
}

describe('validateConfig', () => {
  it('accepts a minimal customer config', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
        ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
      }),
    );
    expect(cfg.mode).toBe('customer');
    expect(cfg.network).toBe('devnet');
    expect(cfg.maxSpendPerJobLamports).toBe(10_000_000n);
    expect(cfg.maxSpendPerHourLamports).toBe(100_000_000n);
    expect(cfg.requireApprovalAboveLamports).toBe(5_000_000n);
    expect(cfg.nostrPrivateKeyHex).toBe(VALID_HEX);
  });

  it('accepts a missing Solana private key (auto-generated by WalletService)', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
      }),
    );
    expect(cfg.solanaPrivateKeyBase58).toBeUndefined();
    expect(cfg.nostrPrivateKeyHex).toBe(VALID_HEX);
  });

  it('accepts a missing Nostr private key (auto-generated by ElisymService)', () => {
    const cfg = envless(() => validateConfig({}));
    expect(cfg.nostrPrivateKeyHex).toBeUndefined();
    expect(cfg.solanaPrivateKeyBase58).toBeUndefined();
  });

  it('rejects an invalid Nostr hex key', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: 'zz',
          ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
        }),
      ),
    ).toThrow();
  });

  it('rejects a too-short Solana key', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PRIVATE_KEY: bs58.encode(new Uint8Array(32)),
        }),
      ),
    ).toThrow(/64-byte secret/);
  });

  it('requires provider capabilities and price in provider mode', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
          ELISYM_MODE: 'provider',
        }),
      ),
    ).toThrow(/Provider mode requires/);
  });

  it('accepts a full provider config', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
        ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
        ELISYM_MODE: 'provider',
        ELISYM_PROVIDER_CAPABILITIES: 'summarization, text/summarize',
        ELISYM_PROVIDER_PRICE_SOL: '0.002',
        ELISYM_PROVIDER_ACTION_MAP: '{"summarization":"SUMMARIZE_TEXT"}',
      }),
    );
    expect(cfg.providerCapabilities).toEqual(['summarization', 'text/summarize']);
    expect(cfg.providerPriceLamports).toBe(2_000_000n);
    expect(cfg.providerActionMap).toEqual({ summarization: 'SUMMARIZE_TEXT' });
  });

  it('rounds 1-lamport SOL amount correctly', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
        ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
        ELISYM_MAX_SPEND_PER_JOB_SOL: '0.000000001',
      }),
    );
    expect(cfg.maxSpendPerJobLamports).toBe(1n);
  });

  it('defaults signerKind to "local"', () => {
    const cfg = envless(() => validateConfig({ ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX }));
    expect(cfg.signerKind).toBe('local');
  });

  it('accepts signerKind=kms when no plaintext key is configured', () => {
    const cfg = envless(() =>
      validateConfig({
        ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
        ELISYM_SIGNER_KIND: 'kms',
      }),
    );
    expect(cfg.signerKind).toBe('kms');
  });

  it('rejects signerKind=kms paired with a plaintext Solana key', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
          ELISYM_SIGNER_KIND: 'kms',
        }),
      ),
    ).toThrow(/ELISYM_SIGNER_KIND must be/);
  });

  it('rejects an unknown signerKind', () => {
    expect(() =>
      envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SIGNER_KIND: 'hardware',
        }),
      ),
    ).toThrow();
  });

  describe('legacy single-product env vars', () => {
    const VALID_PROVIDER_PRODUCTS = JSON.stringify([
      {
        name: 'Echo',
        description: 'Echoes input',
        capabilities: ['echo'],
        priceSol: '0.001',
      },
    ]);

    it('throws when both legacy and PRODUCTS are set', () => {
      expect(() =>
        envless(() =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
            ELISYM_MODE: 'provider',
            ELISYM_PROVIDER_PRODUCTS: VALID_PROVIDER_PRODUCTS,
            ELISYM_PROVIDER_CAPABILITIES: 'echo',
            ELISYM_PROVIDER_PRICE_SOL: '0.001',
          }),
        ),
      ).toThrow(/conflicts with the legacy/);
    });

    it('accepts legacy-only configuration with a single WARN', () => {
      const cfg = envless(() =>
        validateConfig({
          ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
          ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
          ELISYM_MODE: 'provider',
          ELISYM_PROVIDER_CAPABILITIES: 'echo',
          ELISYM_PROVIDER_PRICE_SOL: '0.001',
        }),
      );
      expect(cfg.providerCapabilities).toEqual(['echo']);
      expect(cfg.providerProducts).toBeUndefined();
    });
  });

  describe('server hardening', () => {
    it('refuses mainnet without SECRET_SALT', () => {
      expect(() =>
        envless(
          () =>
            validateConfig({
              ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
              ELISYM_NETWORK: 'mainnet',
            }),
          {
            ELIZA_SERVER_AUTH_TOKEN: 'production-token',
            ELISYM_ALLOW_UNSECURED_RUNTIME: undefined,
          },
        ),
      ).toThrow(/SECRET_SALT/);
    });

    it('refuses mainnet without auth token', () => {
      expect(() =>
        envless(
          () =>
            validateConfig({
              ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
              ELISYM_NETWORK: 'mainnet',
            }),
          { SECRET_SALT: 'a-real-secret-value', ELISYM_ALLOW_UNSECURED_RUNTIME: undefined },
        ),
      ).toThrow(/ELIZA_SERVER_AUTH_TOKEN/);
    });

    it('rejects placeholder SECRET_SALT values', () => {
      expect(() =>
        envless(
          () =>
            validateConfig({
              ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
              ELISYM_NETWORK: 'mainnet',
            }),
          {
            SECRET_SALT: 'changeme',
            ELIZA_SERVER_AUTH_TOKEN: 'real-token',
            ELISYM_ALLOW_UNSECURED_RUNTIME: undefined,
          },
        ),
      ).toThrow(/SECRET_SALT/);
    });

    it('passes mainnet when both SECRET_SALT and auth token are set', () => {
      const cfg = envless(
        () =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_NETWORK: 'mainnet',
          }),
        {
          SECRET_SALT: 'a-real-secret-value',
          ELIZA_SERVER_AUTH_TOKEN: 'real-token',
          ELISYM_ALLOW_UNSECURED_RUNTIME: undefined,
        },
      );
      expect(cfg.network).toBe('mainnet');
    });

    it('refuses provider-with-key on devnet without SECRET_SALT', () => {
      expect(() =>
        envless(
          () =>
            validateConfig({
              ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
              ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
              ELISYM_MODE: 'provider',
              ELISYM_PROVIDER_CAPABILITIES: 'summarization',
              ELISYM_PROVIDER_PRICE_SOL: '0.001',
            }),
          { ELIZA_SERVER_AUTH_TOKEN: 'real-token', ELISYM_ALLOW_UNSECURED_RUNTIME: undefined },
        ),
      ).toThrow(/SECRET_SALT/);
    });

    it('downgrades the error to a WARN when ELISYM_ALLOW_UNSECURED_RUNTIME=true', () => {
      const cfg = envless(
        () =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_NETWORK: 'mainnet',
          }),
        { ELISYM_ALLOW_UNSECURED_RUNTIME: 'true' },
      );
      expect(cfg.network).toBe('mainnet');
    });

    it('does not require hardening for plain customer agents on devnet', () => {
      const cfg = envless(
        () =>
          validateConfig({
            ELISYM_NOSTR_PRIVATE_KEY: VALID_HEX,
            ELISYM_SOLANA_PRIVATE_KEY: VALID_SOLANA,
          }),
        {},
      );
      expect(cfg.mode).toBe('customer');
    });
  });
});
